import type { ExerciseOptions, ScenarioType } from "@/lib/types";

interface ScenarioContent {
  summary: (options: ExerciseOptions) => string;
  objectives: string[];
  discussionQuestions: string[];
  gapQuestions: string[];
  expectedDecisions: string[];
  technicalQuestions: string[];
  complianceQuestions: string[];
  executiveQuestions: string[];
}

export const scenarioContent: Record<ScenarioType, ScenarioContent> = {
  "Phishing / Business Email Compromise": {
    summary: ({ organizationName }) =>
      `${organizationName} receives multiple reports of a suspicious email that appears to come from a senior executive requesting an urgent wire transfer or gift card purchase. One employee clicked the link and entered Microsoft 365 credentials. The IT team is unsure whether the account was accessed, whether mailbox forwarding rules were created, or whether MFA fatigue led to an approval.`,
    objectives: [
      "Validate how suspicious emails and credential exposure are reported.",
      "Confirm who can declare a formal security incident.",
      "Evaluate account containment and password reset procedures.",
      "Review how finance, leadership, and IT coordinate on payment fraud risk.",
      "Identify whether mailbox rule and audit log checks are documented.",
      "Clarify when affected employees and executives are notified.",
    ],
    discussionQuestions: [
      "Who receives the first report of the suspicious email?",
      "Where is the incident documented and tracked?",
      "Who decides whether this becomes a formal incident?",
      "What information must be collected from the user before action is taken?",
      "Who has authority to disable the account or force password resets?",
      "How would the finance team verify whether a payment request was legitimate?",
      "When should leadership be notified?",
      "Who communicates with other employees who may have received the message?",
      "What evidence must be preserved before mailbox changes are made?",
      "What would slow down the response?",
    ],
    gapQuestions: [
      "Does the IRP define severity levels for phishing and business email compromise?",
      "Does the IRP say who can approve containment actions for user accounts?",
      "Are communication templates prepared for phishing alerts?",
      "Does the IRP explain how mailbox rules and sign-in logs should be reviewed?",
      "Is there a documented process for suspected fraudulent payment requests?",
      "Does the plan define when legal, cyber insurance, or compliance teams should be involved?",
      "Are Microsoft 365 or email security contacts documented and current?",
      "Does the IRP require an after-action review after credential exposure?",
    ],
    expectedDecisions: [
      "Whether to disable the affected account.",
      "Whether to revoke sessions and force password resets.",
      "Whether to block sender domains or quarantine similar messages.",
      "Whether to notify all employees about the phishing attempt.",
      "Whether to review wire transfer or payment activity.",
      "Whether to involve cyber insurance or outside incident response support.",
    ],
    technicalQuestions: [
      "Who can review sign-in logs, MFA prompts, mailbox rules, and forwarding settings?",
      "How quickly can active sessions be revoked across cloud applications?",
      "Is there a repeatable checklist for preserving email headers and audit logs?",
    ],
    complianceQuestions: [
      "Could exposed mailbox data include regulated, client, student, or patient information?",
      "Who determines whether notification obligations apply?",
      "Where are regulatory decision notes retained?",
    ],
    executiveQuestions: [
      "Who briefs executives on potential fraud exposure and business impact?",
      "What level of uncertainty is acceptable before leadership alerts finance or customers?",
      "What business process changes would reduce repeat exposure?",
    ],
  },
  Ransomware: {
    summary: ({ organizationName }) =>
      `A user at ${organizationName} reports that files on a shared drive have been renamed and can no longer be opened. A ransom note appears on one workstation, and help desk receives additional reports from nearby teams. IT must determine the spread, isolate affected systems, validate backups, and decide how quickly leadership should be notified.`,
    objectives: [
      "Validate first-response steps for suspected ransomware.",
      "Confirm who can isolate systems and interrupt business processes.",
      "Review backup ownership, recovery expectations, and restoration priority.",
      "Clarify leadership communication during operational disruption.",
      "Identify evidence preservation requirements before rebuilding systems.",
      "Determine how business units prioritize critical services.",
    ],
    discussionQuestions: [
      "Who receives the first report that files are inaccessible?",
      "How is the scope of affected systems documented?",
      "Who decides whether devices or network segments should be isolated?",
      "Which business services are most critical to restore first?",
      "How are backup status and recovery points confirmed?",
      "Who communicates with employees during service disruption?",
      "When should leadership be notified?",
      "What evidence should be preserved before rebuilding a machine?",
      "How would the team handle a ransom demand?",
      "What would slow containment or recovery?",
    ],
    gapQuestions: [
      "Does the IRP define ransomware severity levels and escalation paths?",
      "Does the plan identify who can authorize system isolation?",
      "Are backup owners and recovery time expectations documented?",
      "Does the IRP include decision criteria for taking systems offline?",
      "Are cyber insurance, legal, and law enforcement contacts current?",
      "Are employee and customer communication templates prepared?",
      "Does the plan define evidence collection before restoration?",
      "Is there an after-action review process after recovery?",
    ],
    expectedDecisions: [
      "Whether to disconnect affected devices from the network.",
      "Whether to take shared drives or services offline.",
      "Whether to activate cyber insurance or outside incident response support.",
      "Whether to contact law enforcement.",
      "Whether to restore from backup or preserve systems for investigation.",
      "Whether customers or partners need to be notified.",
    ],
    technicalQuestions: [
      "Who can identify affected endpoints, servers, and file shares?",
      "How are backup integrity and restore points validated?",
      "What logs are needed before systems are rebuilt?",
    ],
    complianceQuestions: [
      "Could the affected systems contain regulated or contractual data?",
      "Who documents the decision not to notify, if notification is not required?",
      "What contractual uptime or reporting obligations may apply?",
    ],
    executiveQuestions: [
      "Which services must be restored first to keep the business operating?",
      "Who approves major business interruption decisions?",
      "What is the executive position on ransom communication and negotiation?",
    ],
  },
  "Data Exfiltration": {
    summary: ({ organizationName }) =>
      `${organizationName} detects an unusual outbound transfer from a file repository to an unknown external destination. Several sensitive folders were accessed shortly before the transfer. The team must determine what data may have left the organization, who was involved, and whether customers, regulators, or partners may be affected.`,
    objectives: [
      "Validate how unusual data movement is escalated.",
      "Confirm ownership for scope determination and evidence collection.",
      "Identify data classification and notification decision points.",
      "Review communication paths between IT, legal, compliance, and leadership.",
      "Determine whether access review procedures are documented.",
      "Clarify how external destinations and user activity are investigated.",
    ],
    discussionQuestions: [
      "Who receives the initial alert about unusual outbound transfer activity?",
      "How is the suspected data set identified?",
      "Who determines whether the activity is authorized?",
      "What information is needed before blocking access or disabling an account?",
      "Who reviews whether sensitive data was involved?",
      "When should legal or compliance teams join the response?",
      "Who communicates with affected business owners?",
      "What evidence must be preserved?",
      "How would the organization determine customer or regulatory impact?",
      "What would slow the investigation?",
    ],
    gapQuestions: [
      "Does the IRP define data exfiltration severity criteria?",
      "Does the plan identify who owns data classification decisions?",
      "Are notification decision workflows documented?",
      "Does the IRP explain how access logs and file activity should be preserved?",
      "Are customer, regulator, and cyber insurance contacts current?",
      "Does the plan include criteria for disabling access during investigation?",
      "Are data owners documented for sensitive repositories?",
      "Does the IRP require an after-action review for data handling improvements?",
    ],
    expectedDecisions: [
      "Whether to disable the user account or block the destination.",
      "Whether to preserve cloud audit logs immediately.",
      "Whether to notify data owners and leadership.",
      "Whether legal or compliance must lead notification analysis.",
      "Whether to involve outside forensic support.",
      "Whether customers, partners, or regulators require notification.",
    ],
    technicalQuestions: [
      "Which logs show file access, download volume, source IP, and destination?",
      "How long are relevant cloud and network logs retained?",
      "Can the team distinguish preview, sync, download, and external sharing activity?",
    ],
    complianceQuestions: [
      "What laws, contracts, or policies apply to the potentially exposed data?",
      "Who maintains the notification timeline and decision record?",
      "Are breach notification contacts and templates ready?",
    ],
    executiveQuestions: [
      "Who briefs leadership before facts are fully confirmed?",
      "How much uncertainty is acceptable before notifying key customers?",
      "What business relationships could be affected by the suspected exposure?",
    ],
  },
  "Compromised Admin Account": {
    summary: ({ organizationName }) =>
      `${organizationName} identifies a suspicious privileged login from an unfamiliar location. Shortly after the login, new accounts and permission changes appear in administrative audit logs. The team must decide how to revoke access, preserve logs, review Conditional Access controls, and determine whether additional systems were affected.`,
    objectives: [
      "Validate privileged account compromise response procedures.",
      "Confirm who can revoke admin sessions and reset credentials.",
      "Review audit log ownership and preservation steps.",
      "Clarify escalation to leadership when core systems may be affected.",
      "Identify how permission changes and new accounts are reviewed.",
      "Evaluate whether emergency access accounts are documented.",
    ],
    discussionQuestions: [
      "Who receives the alert about the suspicious privileged login?",
      "Who can confirm whether the activity is legitimate?",
      "What immediate containment actions are available?",
      "Who has authority to revoke sessions or remove admin roles?",
      "How are new accounts and permission changes reviewed?",
      "When should leadership be notified?",
      "What systems could be affected by this administrator account?",
      "What evidence must be preserved before permissions are changed?",
      "Who communicates with vendors or MSP contacts if they manage the account?",
      "What would slow down containment?",
    ],
    gapQuestions: [
      "Does the IRP define escalation for privileged account compromise?",
      "Does the plan say who can approve admin role removal?",
      "Are Conditional Access and MFA review steps documented?",
      "Does the IRP explain how to preserve admin audit logs?",
      "Are emergency access procedures documented and tested?",
      "Are vendor or MSP administrator contacts current?",
      "Does the plan define business impact if admin access is interrupted?",
      "Does the IRP require a post-incident privileged access review?",
    ],
    expectedDecisions: [
      "Whether to revoke all active administrator sessions.",
      "Whether to disable or reset privileged accounts.",
      "Whether to remove newly created accounts or permissions.",
      "Whether to pause changes in affected systems.",
      "Whether to involve cyber insurance or forensic support.",
      "Whether customers or partners need notification.",
    ],
    technicalQuestions: [
      "Who can export administrator audit logs and sign-in history?",
      "How are OAuth apps, service accounts, and delegated permissions reviewed?",
      "What Conditional Access policies would have reduced the risk?",
    ],
    complianceQuestions: [
      "Could the compromised administrator access regulated systems or data?",
      "Who records the scope and notification decision?",
      "Are privileged access review records required by policy or contract?",
    ],
    executiveQuestions: [
      "What critical systems depend on the affected administrator account?",
      "Who approves actions that may interrupt administrative access?",
      "What assurance does leadership need before declaring containment?",
    ],
  },
  "Lost or Stolen Laptop": {
    summary: ({ organizationName }) =>
      `An employee at ${organizationName} reports that a company laptop is missing after travel. The user is unsure when it was last seen and may have stored files locally. The team must confirm encryption status, determine whether remote wipe is possible, review data exposure, and evaluate whether the reporting timeline affects notification obligations.`,
    objectives: [
      "Validate lost device reporting and escalation steps.",
      "Confirm device encryption and remote wipe verification procedures.",
      "Review how locally stored data is assessed.",
      "Clarify HR, legal, compliance, and manager involvement.",
      "Identify communication requirements for missing assets.",
      "Determine whether asset inventory data is complete.",
    ],
    discussionQuestions: [
      "Who receives the first report of the missing laptop?",
      "What details must the employee provide?",
      "Where is the missing device documented?",
      "Who checks encryption and management status?",
      "Who decides whether to trigger remote wipe?",
      "How is locally stored data assessed?",
      "When should legal or compliance be notified?",
      "Who communicates with the employee's manager?",
      "What evidence or records must be preserved?",
      "What would slow the response?",
    ],
    gapQuestions: [
      "Does the IRP or asset policy define missing device severity levels?",
      "Does the plan identify who can approve remote wipe?",
      "Are encryption status and device inventory records easy to access?",
      "Does the plan explain how to assess locally stored data?",
      "Are employee reporting timelines defined?",
      "Does the plan include notification decision criteria?",
      "Are HR and manager communication responsibilities documented?",
      "Does the plan require an after-action review for asset control gaps?",
    ],
    expectedDecisions: [
      "Whether to remotely lock or wipe the device.",
      "Whether to disable account sessions from the device.",
      "Whether to classify the event as a security incident.",
      "Whether legal or compliance must assess notification obligations.",
      "Whether to notify customers or regulators.",
      "Whether to update travel and device handling procedures.",
    ],
    technicalQuestions: [
      "Who can verify disk encryption, last check-in time, and remote wipe status?",
      "Can the team identify synced folders or cached data?",
      "What logs show whether the device accessed cloud systems after it went missing?",
    ],
    complianceQuestions: [
      "Does encryption status change notification requirements?",
      "Could locally stored files include regulated data?",
      "Who documents the legal or compliance decision?",
    ],
    executiveQuestions: [
      "What business risk remains if the device never checks in again?",
      "Who signs off on the final exposure determination?",
      "What policy changes would reduce future lost-device risk?",
    ],
  },
  "Vendor / Third-Party Breach": {
    summary: ({ organizationName }) =>
      `A vendor notifies ${organizationName} that its environment was compromised and that shared customer or operational data may have been accessed. The organization must determine what data was provided to the vendor, review contract and notification obligations, coordinate with the vendor, and understand possible customer impact.`,
    objectives: [
      "Validate third-party incident escalation procedures.",
      "Confirm vendor contact, contract, and data owner records.",
      "Review notification and customer impact decision paths.",
      "Clarify legal, compliance, procurement, and leadership roles.",
      "Identify evidence needed from the vendor.",
      "Determine how vendor updates are tracked.",
    ],
    discussionQuestions: [
      "Who receives vendor breach notifications?",
      "Where is the vendor incident documented?",
      "Who owns the vendor relationship?",
      "What data was shared with the vendor?",
      "Who reviews contract notification obligations?",
      "When should leadership be notified?",
      "Who communicates with customers if needed?",
      "What questions must be sent back to the vendor?",
      "How often should vendor status updates be requested?",
      "What would slow down decision-making?",
    ],
    gapQuestions: [
      "Does the IRP include third-party breach procedures?",
      "Are vendor data owners and business owners documented?",
      "Are contract notification requirements easy to locate?",
      "Does the plan define who communicates with the vendor?",
      "Are customer and regulator notification workflows documented?",
      "Are cyber insurance and legal contacts current?",
      "Does the plan include vendor evidence request templates?",
      "Does the IRP require an after-action review of vendor risk management?",
    ],
    expectedDecisions: [
      "Whether to suspend the vendor connection or service.",
      "Whether to request forensic details from the vendor.",
      "Whether contract notification deadlines have started.",
      "Whether customers, partners, or regulators need notification.",
      "Whether to involve cyber insurance or outside counsel.",
      "Whether to update vendor risk ratings or contract terms.",
    ],
    technicalQuestions: [
      "What systems, integrations, APIs, or data transfers connect to the vendor?",
      "Can vendor access be limited while business operations continue?",
      "What logs show recent vendor activity in the environment?",
    ],
    complianceQuestions: [
      "What contractual breach notification timelines apply?",
      "What data processing or regulatory obligations apply to this vendor?",
      "Who owns the official notification record?",
    ],
    executiveQuestions: [
      "What customer relationships could be affected by the vendor event?",
      "Who approves continuing or pausing vendor service?",
      "What public message is needed if the incident becomes visible?",
    ],
  },
  "Insider Threat": {
    summary: ({ organizationName }) =>
      `${organizationName} notices unusual activity from an employee account, including large file downloads and access to folders unrelated to the employee's role. A manager has also reported concerning behavior. The team must coordinate carefully with HR and legal, preserve evidence, evaluate access removal, and avoid tipping off the employee prematurely.`,
    objectives: [
      "Validate insider threat escalation and confidentiality procedures.",
      "Confirm HR, legal, manager, and IT coordination points.",
      "Review evidence preservation before access changes.",
      "Clarify access removal authority and timing.",
      "Identify communication restrictions during sensitive investigations.",
      "Determine whether data exposure or theft may have occurred.",
    ],
    discussionQuestions: [
      "Who receives the first report of suspicious employee behavior?",
      "Who decides whether this is an HR matter, security matter, or both?",
      "How is information shared without spreading rumors?",
      "What evidence must be preserved before access is changed?",
      "Who can approve access suspension or removal?",
      "When should legal be involved?",
      "Who communicates with the employee's manager?",
      "How would the team determine what data was accessed or downloaded?",
      "What documentation is required for employment action?",
      "What would slow a coordinated response?",
    ],
    gapQuestions: [
      "Does the IRP include insider threat procedures?",
      "Does the plan identify HR and legal decision points?",
      "Are evidence preservation requirements documented?",
      "Does the plan define who can approve access removal?",
      "Are confidentiality expectations clear?",
      "Does the plan address employee-owned devices or remote work scenarios?",
      "Are data owner contacts documented for sensitive repositories?",
      "Does the IRP require an after-action review after insider events?",
    ],
    expectedDecisions: [
      "Whether to monitor, restrict, or remove access.",
      "Whether HR or legal leads the investigation.",
      "Whether to preserve devices or cloud audit logs.",
      "Whether to notify leadership.",
      "Whether customers, partners, or regulators may need notification.",
      "Whether law enforcement should be contacted.",
    ],
    technicalQuestions: [
      "Which systems can show large downloads, external shares, and unusual access?",
      "How quickly can access be removed across all applications?",
      "Can evidence be preserved without alerting the employee?",
    ],
    complianceQuestions: [
      "Could downloaded data trigger privacy, contractual, or regulatory obligations?",
      "Who approves monitoring or investigation steps involving an employee?",
      "Where is the investigation decision record retained?",
    ],
    executiveQuestions: [
      "Who needs to know, and who should not be informed yet?",
      "What business disruption could result from immediate access removal?",
      "What standard of proof is needed before action is taken?",
    ],
  },
  "Cloud Misconfiguration": {
    summary: ({ organizationName }) =>
      `${organizationName} learns that a cloud storage location may have been publicly exposed. Sensitive files could have been accessible without the intended permissions. The team must review access settings, logging, remediation steps, and whether exposure creates customer, contractual, or regulatory notification obligations.`,
    objectives: [
      "Validate cloud misconfiguration escalation and containment steps.",
      "Confirm who owns cloud access review and remediation.",
      "Review logging and exposure scope procedures.",
      "Clarify notification decision points for potentially exposed data.",
      "Identify communication paths between IT, data owners, and leadership.",
      "Determine whether preventive configuration controls are documented.",
    ],
    discussionQuestions: [
      "Who receives the report of the public cloud exposure?",
      "Who confirms whether the storage was actually public?",
      "What data was stored in the exposed location?",
      "Who can change permissions or take the resource offline?",
      "What logs show whether files were accessed?",
      "Who contacts the business owner of the data?",
      "When should leadership be notified?",
      "Who determines customer or regulatory impact?",
      "What evidence must be preserved before permissions are changed?",
      "What would slow remediation?",
    ],
    gapQuestions: [
      "Does the IRP define cloud misconfiguration severity levels?",
      "Does the plan identify cloud resource owners?",
      "Are access review and permission rollback steps documented?",
      "Does the IRP explain how cloud logs should be preserved?",
      "Are data classification and notification workflows documented?",
      "Are cloud provider and MSP contacts current?",
      "Does the plan define who can approve public access exceptions?",
      "Does the IRP require an after-action review of cloud controls?",
    ],
    expectedDecisions: [
      "Whether to remove public access immediately.",
      "Whether to take the storage location offline.",
      "Whether to preserve logs before remediation.",
      "Whether data owners and leadership need immediate notification.",
      "Whether customers, partners, or regulators need notification.",
      "Whether to implement additional cloud guardrails.",
    ],
    technicalQuestions: [
      "Which logs show object access, permission changes, and anonymous reads?",
      "Can the team identify who made the configuration change?",
      "Are automated controls available to detect public exposure?",
    ],
    complianceQuestions: [
      "What regulated or contractual data may have been exposed?",
      "Who determines whether access equals reportable exposure?",
      "What notification deadlines could apply?",
    ],
    executiveQuestions: [
      "What customer or reputational impact could result from the exposure?",
      "Who approves the final notification decision?",
      "What investment would prevent repeat cloud misconfiguration?",
    ],
  },
};
